### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by x0n4d0** [x0n4d0/flappy-bird-js#1]
- [ ] Split original do passaro.png
- [ ] Refatorar organização do projeto para MVC
- [ ] Arquivo para o cenário (...nuvem.png)
- [ ] Criar start/stop/reset do game
- [ ] Definir seta ou clique do mouse para o movimento do passaro
